version: '3'
services:
  redis:
    image: redis:alpine
  mongo:
    image: mvertes/alpine-mongo:latest
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8005:8005
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongo
      - WEB_HOST=web
    links:
      - redis
      - mongo
